# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-03 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cms_dj_artical',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('cms_dj_url', models.CharField(max_length=255)),
                ('cms_dj_tag', models.CharField(max_length=255)),
                ('cms_dj_addtime', models.CharField(max_length=255)),
                ('cms_dj_author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='cms_dj_login',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('cms_dj_username', models.CharField(max_length=255)),
                ('cms_dj_password', models.CharField(max_length=255)),
            ],
        ),
    ]
